temp-folder: "xrf_explorer/server/temp"
uploads-folder: "xrf_explorer/server/data"
upload-buffer-size: 16384
dim-reduction:
  folder: "xrf_explorer/server/temp/dim_reduction"
  umap-parameters:
    n-neighbors: 10
    min-dist: 0
    n-components: 2
    metric: "cosine"
color-segmentation:
  k-means-parameters:
    k: 20
    nr-attempts: 10
    image-width: 500
    image-height: 500
  elemental-k-means-parameters:
    k: 2
    nr-attempts: 10
    elem-threshold: 0.1
