temp-folder: "xrf_explorer/server/temp"
uploads-folder: "xrf_explorer/server/data"
generated-folder-name: "generated"
bind-address: 127.0.0.1
port: 8001
upload-buffer-size: 16384
max-spectrum-points: 400
dim-reduction:
  folder-name: "dim_reduction"
  max-samples: 50000
  umap-parameters:
    n-neighbors: 10
    min-dist: 0
    n-components: 2
    metric: "cosine"
color-segmentation:
  folder-name: "generated_cs"
  k-means-parameters:
    k: 10
    nr-attempts: 10
  elemental-k-means-parameters:
    k: 5
    nr-attempts: 10
    elem-threshold: 40 # range [0,255]
