temp-folder: "xrf_explorer/server/temp"
uploads-folder: "xrf_explorer/server/data"
bind-address: 127.0.0.1
port: 8001
upload-buffer-size: 16384
dim-reduction:
  folder: "xrf_explorer/server/temp/dim_reduction"
  umap-parameters:
    n-neighbors: 10
    min-dist: 0
    n-components: 2
    metric: "cosine"
color-segmentation:
  folder: "xrf_explorer/server/temp/color_segmentation"
  k-means-parameters:
    k: 10
    nr-attempts: 10
  elemental-k-means-parameters:
    k: 5
    nr-attempts: 10
    elem-threshold: 40.0 # range [0,255]
