temp-folder: "xrf_explorer/server/temp"
uploads-folder: "xrf_explorer/server/data"
upload-buffer-size: 16384
dim-reduction:
  folder: "xrf_explorer/server/temp/dim_reduction"
  umap-parameters:
    n-neighbors: 10
    min-dist: 0
    n-components: 2
    metric: "cosine"
color-segmentation:
  folder: "xrf_explorer/server/temp/color_segmentation"
  k-means-parameters:
    k: 25
    nr-attempts: 10
    image-width: 400
    image-height: 600
  elemental-k-means-parameters:
    k: 25
    nr-attempts: 10
    elem-threshold: 20
