name: Run Python Tests

on: [push]

jobs:
  build:
    name: Run all Python Tests
    runs-on: self-hosted
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Europe/Amsterdam'

      - name: Set Up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run PyTest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          emoji: false
          verbose: false
          job-summary: true
          report-title: "Test Report on branch '${{ steps.extract_branch.outputs.branch }}'"