name: Run Python Tests

on: [push, pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Europe/Amsterdam'

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install pytest pytest-md pytest-emoji

      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true
          report-title: 'Test Report on branch: ${{ steps.extract_branch.outputs.branch }}'